create extension if not exists pgcrypto;

create table if not exists bills (
  id bigint generated by default as identity primary key,
  customer_name text,
  invoice_no bigint not null,
  date date not null default current_date,
  items jsonb not null default '[]'::jsonb,
  total numeric(12, 2) not null default 0,
  advance numeric(12, 2) not null default 0,
  grand_total numeric(12, 2) not null default 0,
  token uuid not null default gen_random_uuid() unique,
  created_at timestamptz not null default now()
);

create table if not exists settings (
  key text primary key,
  value text not null
);

create table if not exists suggestions (
  id bigint generated by default as identity primary key,
  description text not null unique,
  default_rate numeric(12, 2)
);

insert into settings (key, value)
values
  ('contact_name1', 'Dilip Ramjiyani'),
  ('contact_phone1', '+91 91580 78649'),
  ('contact_name2', 'Anuj Ramjiyani'),
  ('contact_phone2', '+91 73856 89102'),
  ('upi_id', 'dilipramjiyani4780-1@oksbi'),
  ('upi_name', 'Dilip Ramjiyani')
on conflict (key) do update set value = excluded.value;

alter table bills enable row level security;
alter table settings enable row level security;
alter table suggestions enable row level security;

drop policy if exists "public read bills" on bills;
drop policy if exists "public insert bills" on bills;
drop policy if exists "public delete bills" on bills;
drop policy if exists "public read settings" on settings;
drop policy if exists "public upsert settings" on settings;
drop policy if exists "public read suggestions" on suggestions;
drop policy if exists "public write suggestions" on suggestions;

create policy "public read bills" on bills
for select using (true);

create policy "public insert bills" on bills
for insert with check (true);

create policy "public delete bills" on bills
for delete using (true);

create policy "public read settings" on settings
for select using (true);

create policy "public upsert settings" on settings
for all using (true) with check (true);

create policy "public read suggestions" on suggestions
for select using (true);

create policy "public write suggestions" on suggestions
for all using (true) with check (true);

